# tag::configurationSettings[]
org:
    grails:
        plugins:
            googlecloud:
                storage:
                    bucket: grails-bookshelf.appspot.com
---
bookshelf:
    persistenceType: cloudSQL
    storageType: cloudStorage
    limit: 10
    orderBy: title
    callback: http://localhost:8080/oauth2callback
    defaultLanguageCode: en
    localizations:
        - it
        - es
    localStorageFolder: /Users/sdelamo/Sites/bookshelf
    localDataUrl: http://localhost:8888
---
# end::configurationSettings[]
grails:
    profile: web
    codegen:
        defaultPackage: bookshelf
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 26214400
            maxRequestSize: 26214400
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
environments:
    development:
        dataSource:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            dbCreate: create-drop
            url: jdbc:mysql://127.0.0.1:8889/grailsbookshelf_dev?useTimezone=true&serverTimezone=GMT
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password: root
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
