version: 2
jobs:
  build:
    docker:
      - image: python:latest
    steps:
      - checkout
      - restore_cache:
          key: lint-flake8
      - run:
          name: Install Flake8
          command: pip install --upgrade --user flake8
      - run:
          name: Create package list (for caching)
          command: pip freeze --user > ./requirement.txt
      - save_cache:
          paths:
            - ~/.local
          key: lint-flake8-{{ checksum "./requirement.txt" }}
      - run:
          name: OS release
          command: cat /etc/debian_version
      - run:
          name: Kernel version
          command: uname -a
      - run:
          name: Python version
          command: python --version
      - run:
          name: Flake8 version
          command: ~/.local/bin/flake8 --version
      - run:
          name: Run Flake8
          command: ~/.local/bin/flake8 --ignore=E111,E114,E121 --max-line-length=100 --show-source --statistics .
